Added explicit dependency on Unidecode
Without this explicit dependency when one does

 pip3 install -r requirements/local.txt

as required by docs/install.rst, the following error comes up:

 ERROR: django-filer 1.4.4 has requirement Unidecode<1.1,>=0.04, but
        you'll have unidecode 1.1.1 which is incompatible.

That happens because the requirement python-slugify==2.0.1 pulls
Unidecode-version 1.1.1. So adding the explicit requirement before
python-slugify pulls the correct version needed later on by
django-filer.